device: cuda

storage:
  detection weights: /ml/Imagn/models/llama_unsloth_graded_350_350
  caption weights: /ml/Imagn/models/llama_playercaptions_conf_275_350p2 
  player_info: /ml/Imagn/nfl_player_info.json
  player_map: /ml/Imagn/train_data/source_files/nfl_player_map.json

container:
  detection weights: detection_wts
  caption weights: caption_wts 
  player_info: player_info.json
  player_map: player_map.json

model:
  teams: 
    - Kansas City Chiefs
    - Philadelphia Eagles
  fps: 0.5
  allow_single_frame: true